
# Site settings
title: Baobab
subtitle: lab Meeting 
baseurl:
url: labmeeting #https://baobablab.github.io/


# Contacts
email:
author:
street_address:
city:
state: 
zip_code:
country: France
phone:

# Expiration in days
expiration_news: 90
expiration_events: 700

# Social settings
neurospin_url: https://joliot.cea.fr/drf/joliot/Pages/Entites_de_recherche/NeuroSpin.aspx
github_url: https://github.com/baobablab/labmeeting

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown

# Collections
collections_dir: _collections
collections:

  events:
    output    : true
    permalink : /:collection/:path

  news:
    output    : true
    permalink : /news/:title/index.html

  contacts:
    output    : true
    permalink : /contacts/:title/index.html

